# Generated by Django 3.2.4 on 2021-08-04 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('notice', models.TextField(blank=True)),
                ('row', models.IntegerField()),
                ('minimum', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('a', '가능'), ('u', '불가능')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('point', models.IntegerField(default=100)),
                ('status', models.CharField(blank=True, choices=[('a', '재학'), ('b', '휴학'), ('d', '자퇴'), ('k', '퇴학')], default='a', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('num', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('a', '가능'), ('u', '불가능')], default='a', max_length=1)),
                ('ban_list', models.ManyToManyField(related_name='banned_seat_set', to='point.Student')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='point.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.room')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('u', '사용'), ('c', '취소'), ('t', '선생님')], default='t', max_length=1)),
                ('obj_name', models.CharField(max_length=32)),
                ('obj_id', models.IntegerField(null=True)),
                ('point', models.IntegerField()),
                ('canceled', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('cancel_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='point.log')),
                ('log_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.student')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('submit', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='point.student')),
            ],
        ),
    ]
