# Generated by Django 3.2 on 2021-06-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatLog',
        ),
    ]
