# Generated by Django 5.2.17 on 2026-08-25 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='preset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='log',
            name='cancel_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point.log'),
        ),
        migrations.AlterField(
            model_name='room',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='point.student'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['obj_name', 'obj_id', 'canceled'], name='point_log_obj_nam_b66ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['log_student', '-created_date'], name='point_log_log_stu_a04198_idx'),
        ),
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(condition=models.Q(('canceled', False), ('status', 'u')), fields=('obj_name', 'obj_id', 'log_student'), name='one_active_bid_per_seat_per_student'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'num'), name='unique_seat_num_per_room'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('point__gte', 0)), name='student_point_not_negative'),
        ),
    ]
