# Generated by Django 3.2 on 2021-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='owner',
            field=models.IntegerField(null=True),
        ),
    ]
