# Generated by Django 3.2 on 2021-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_seat_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.IntegerField()),
                ('seat_num', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
