# Generated by Django 3.2 on 2021-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_auto_20210615_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
